config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :donations
  resources :projects
  resources :donors
  resources :expenses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donor
  belongs_to :project

  validates :total_value, presence: true
  validates :date, presence: true
  validates :payment_method, presence: true
end

app/models/donor.rb
class Donor < ApplicationRecord
    has_many :donations
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :project

  validates :name, presence: true
  validates :description, presence: true
  validates :total_value, numericality: { greater_than_or_equal_to: 0 }
  validates :supplier_identification_number, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :donations
    has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: %i[ show edit update destroy ]

  # GET /donations or /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1 or /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations or /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: "Donation was successfully created." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1 or /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1 or /donations/1.json
  def destroy
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_path, status: :see_other, notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      params.require(:donation).permit(:total_value, :date, :payment_method, :donor_id, :project_id)
    end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: %i[ show edit update destroy ]

  # GET /donors or /donors.json
  def index
    @donors = Donor.all
  end

  # GET /donors/1 or /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors or /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: "Donor was successfully created." }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1 or /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: "Donor was successfully updated." }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1 or /donors/1.json
  def destroy
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_path, status: :see_other, notice: "Donor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donor_params
      params.require(:donor).permit(:name, :cellphone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :city, :target_value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/donations/_donation.html.erb
<div id="<%= dom_id donation %>">
  <p>
    <strong>Total value:</strong>
    <%= donation.total_value %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= donation.date %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= donation.payment_method %>
  </p>

</div>

app/views/donations/_form.html.erb
<%= form_with(model: donation) do |form| %>
  <% if donation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
        <% donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :total_value, style: "display: block" %>
    <%= form.text_field :total_value %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.text_field :payment_method %>
  </div>

  <div class="field">
  <%= form.label :donor_id, "Donor" %>
  <%= form.collection_select :donor_id, Donor.all, :id, :name, prompt: "Select Donor" %>
</div>

<div class="field">
  <%= form.label :project_id, "Project" %>
  <%= form.collection_select :project_id, Project.all, :id, :name, prompt: "Select Project" %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Show this donation", @donation %> |
  <%= link_to "Back to donations", donations_path %>
</div>

app/views/donations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Donations</h1>

<div id="donations">
  <% @donations.each do |donation| %>
    <%= render donation %>
    <p>
      <%= link_to "Show this donation", donation %>
    </p>
  <% end %>
</div>

<%= link_to "New donation", new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Back to donations", donations_path %>
</div>

app/views/donations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @donation %>

<div>
  <%= link_to "Edit this donation", edit_donation_path(@donation) %> |
  <%= link_to "Back to donations", donations_path %>

  <%= button_to "Destroy this donation", @donation, method: :delete %>
</div>

app/views/donors/_donor.html.erb
<div id="<%= dom_id donor %>">
  <p>
    <strong>Name:</strong>
    <%= donor.name %>
  </p>

  <p>
    <strong>Cellphone:</strong>
    <%= donor.cellphone %>
  </p>

</div>

app/views/donors/_form.html.erb
<%= form_with(model: donor) do |form| %>
  <% if donor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
        <% donor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cellphone, style: "display: block" %>
    <%= form.text_field :cellphone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render "form", donor: @donor %>

<br>

<div>
  <%= link_to "Show this donor", @donor %> |
  <%= link_to "Back to donors", donors_path %>
</div>

app/views/donors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Donors</h1>

<div id="donors">
  <% @donors.each do |donor| %>
    <%= render donor %>
    <p>
      <%= link_to "Show this donor", donor %>
    </p>
  <% end %>
</div>

<%= link_to "New donor", new_donor_path %>

app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render "form", donor: @donor %>

<br>

<div>
  <%= link_to "Back to donors", donors_path %>
</div>

app/views/donors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @donor %>

<div>
  <%= link_to "Edit this donor", edit_donor_path(@donor) %> |
  <%= link_to "Back to donors", donors_path %>

  <%= button_to "Destroy this donor", @donor, method: :delete %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('home.title') %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
</head>

<body>
  <header>
    <nav>
      <%= link_to t('home.title'), root_path %> |
      <%= link_to t('donations'), donations_path %> |
      <%= link_to t('projects'), projects_path %> |
      <%= link_to t('donors'), donors_path %> |
      <%= link_to t('expenses'), expenses_path %>
    </nav>
  </header>

  <main>
    <h1><%= t('home.welcome') %></h1>
    <p>Estamos felizes em tê-lo aqui. Explore nossos projetos, faça doações e ajude-nos a fazer a diferença!</p>
  </main>

  <footer>
    <p>&copy; <%= Time.now.year %> <%=  t('project_title') %>. <%= t('home.footer') %></p>
  </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('home.title') %> | Donate</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
</head>

<body>
  <main>
    <%= yield %>
  </main>

  <footer>
    <p><%= t('home.footer') %></p>
  </footer>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :target_value, style: "display: block" %>
    <%= form.text_field :target_value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>City:</strong>
    <%= project.city %>
  </p>

  <p>
    <strong>Target value:</strong>
    <%= project.target_value %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>